import type { Metadata } from 'next';
import { Roboto_Flex } from 'next/font/google';

import Aside from './_components/Aside';
import Footer from './_components/Footer';
import Nav from './_components/Nav';

import './globals.css';

const roboto_flex = Roboto_Flex({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${roboto_flex.className} overflow-x-hidden bg-grayLight`}
      >
        <Nav />
        <Aside />
        {children}
        <Footer />
      </body>
    </html>
  );
}
